In [8]:
import os

from dotenv import load_dotenv

load_dotenv()

con = (
    f"postgresql://robot-startml-ro:{os.environ['password']}@"
    "postgres.lab.karpov.courses:6432/startml"
)

In [ ]:
import pandas as pd

df = pd.read_sql(
    """SELECT * FROM "feed_action" LIMIT 10 """,
    con=con,
)

df.head()

   user_id  post_id action                time        id
0   111680      381   view 2021-10-24 23:56:12  54010497
1   111048      428   view 2021-10-24 23:56:12  54010498
2   107336      275   view 2021-10-24 23:56:13  54010499
3   108484      359   view 2021-10-24 23:56:13  54010500
4     1127      332   view 2021-10-24 23:56:14  54010501

In [ ]:
df = pd.read_sql(
    """SELECT * FROM "user" LIMIT 10 """,
    con=con,
)

df.head(20)

    id  gender  age country               city  exp_group       os source
0  200       1   34  Russia          Degtyarsk          3  Android    ads
1  201       0   37  Russia             Abakan          0  Android    ads
2  202       1   17  Russia           Smolensk          4  Android    ads
3  203       0   18  Russia             Moscow          1      iOS    ads
4  204       0   36  Russia  Anzhero-Sudzhensk          3  Android    ads
5  205       0   32  Russia         Dugulubgey          3  Android    ads
6  206       1   20  Russia            Kamenka          1  Android    ads
7  207       1   27  Russia            Groznyy          3      iOS    ads
8  208       1   17  Russia               Zima          1  Android    ads
9  209       0   17  Russia       Yuzhnouralsk          1  Android    ads

In [ ]:
df = pd.read_sql(
    """SELECT * FROM "post" LIMIT 10 """,
    con=con,
)
df.head(20)

     id                                               text     topic
0     1  UK economy facing major risks\n\nThe UK manufa...  business
1     2  Aids and climate top Davos agenda\n\nClimate c...  business
2     3  Asian quake hits European shares\n\nShares in ...  business
3     4  India power shares jump on debut\n\nShares in ...  business
4     5  Lacroix label bought by US firm\n\nLuxury good...  business
5     6  Insurance bosses plead guilty\n\nAnother three...  business
6    14  Saudi investor picks up the Savoy\n\nLondons f...  business
7  2366  RACV | Annual cost of owning and maintaining a...     covid
8     7  Turkey-Iran mobile deal at risk\n\nTurkeys inv...  business
9     8  Parmalat to return to stockmarket\n\nParmalat,...  business

In [7]:
df["topic"].unique()

array(['business', 'covid'], dtype=object)

In [14]:
print(len(df), df.loc[df["text"].str.len().idxmax(), "text"])

10 Asian quake hits European shares

Shares in Europes leading reinsurers and travel firms have fallen as the scale of the damage wrought by tsunamis across south Asia has become apparent.

More than 23,000 people have been killed following a massive underwater earthquake and many of the worst hit areas are popular tourist destinations. Reisurance firms such as Swiss Re and Munich Re lost value as investors worried about rebuilding costs. But the disaster has little impact on stock markets in the US and Asia.

Currencies including the Thai baht and Indonesian rupiah weakened as analysts warned that economic growth may slow. It came at the worst possible time, said Hans Goetti, a Singapore-based fund manager. The impact on the tourist industry is pretty devastating, especially in Thailand. Travel-related shares dropped in Europe, with companies such as Germanys TUI and Lufthansa and Frances Club Mediterranne sliding. Insurers and reinsurance firms were also under pressure in Europe.

Shares in Munich Re and Swiss Re - the worlds two biggest reinsurers - both fell 1.7% as the market speculated about the cost of rebuilding in Asia. Zurich Financial, Allianz and Axa also suffered a decline in value.

However, their losses were much smaller, reflecting the markets view that reinsurers were likely to pick up the bulk of the costs. Worries about the size of insurance liabilities dragged European shares down, although the impact was exacerbated by light post-Christmas trading. Germanys benchmark Dax index closed the day 16.29 points lower at 3.817.69 while Frances Cac index of leading shares fell 5.07 points to 3.817.69. Investors pointed out, however, that declines probably would be industry specific, with the travel and insurance firms hit hardest. Its still too early for concrete damage figures, Swiss Res spokesman Floiran Woest told Associated Press. That also has to do with the fact that the damage is very widely spread geographically.

The unfolding scale of the disaster in south Asia had little immediate impact on US shares, however. The Dow Jones index had risen 20.54 points, or 0.2%, to 10,847.66 by late morning as analsyts were cheered by more encouraging reports from retailers about post-Christmas sales. In Asian markets, adjustments were made quickly to account for lower earnings and the cost of repairs. Thai Airways shed almost 4%. The country relies on tourism for about 6% of its total economy. Singapore Airlines dropped 2.6%. About 5% of Singapores annual gross domestic product (GDP) comes from tourism. Malaysias budget airline, AirAsia fell 2.9%. Resort operator Tanco Holdings slumped 5%.

Travel companies also took a hit, with Japans Kinki Nippon sliding 1.5% and HIS dropping 3.3%. However, the overall impact on Asias largest stock market, Japans Nikkei, was slight. Shares fell just 0.03%. Concerns about the strength of economic growth going forward weighed on the currency markets. The Indonesian rupiah lost as much as 0.6% against the US dollar, before bouncing back slightly to trade at 9,300. The Thai baht lost 0.3% against the US currency, trading at 39.10. In India, where more than 2,000 people are thought to have died, the rupee shed 0.1% against the dollar Analysts said that it was difficult to predict the total cost of the disaster and warned that share prices and currencies would come under increasing pressure as the bills mounted.

In [ ]:
df = pd.read_sql(
    """SELECT distinct("topic") FROM "post" LIMIT 10 """,
    con=con,
)
df.head(20)

           topic
0           tech
1          covid
2          movie
3  entertainment
4       politics
5          sport
6       business

In [ ]:
df = pd.read_sql(
    """SELECT *FROM "user" """,
    con=con,
)
df.head(20)

     id  gender  age  country               city  exp_group       os source
0   200       1   34   Russia          Degtyarsk          3  Android    ads
1   201       0   37   Russia             Abakan          0  Android    ads
2   202       1   17   Russia           Smolensk          4  Android    ads
3   203       0   18   Russia             Moscow          1      iOS    ads
4   204       0   36   Russia  Anzhero-Sudzhensk          3  Android    ads
5   205       0   32   Russia         Dugulubgey          3  Android    ads
6   206       1   20   Russia            Kamenka          1  Android    ads
7   207       1   27   Russia            Groznyy          3      iOS    ads
8   208       1   17   Russia               Zima          1  Android    ads
9   209       0   17   Russia       Yuzhnouralsk          1  Android    ads
10  210       0   39  Ukraine           Mykolaiv          3  Android    ads
11  211       1   22  Belarus              Minsk          0      iOS    ads
12  212       1   47   Russia            Podolsk          0      iOS    ads
13  213       1   22  Ukraine          Kamianske          2      iOS    ads
14  214       0   21   Russia             Moscow          4  Android    ads
15  215       1   18  Ukraine          Horodenka          3      iOS    ads
16  216       0   38  Ukraine               Lviv          1  Android    ads
17  217       1   29   Russia              Kansk          3      iOS    ads
18  218       1   25  Belarus              Minsk          2      iOS    ads
19  219       0   36   Russia             Moscow          2  Android    ads

In [17]:
len(df)

163205

In [19]:
result = df[(df["age"]>30) & (df["os"]=="iOS")]

In [22]:
print(result.iloc[0]["id"], result.iloc[0]["city"])

212 Podolsk

In [26]:
df.head(20)

     id  gender  age  country               city  exp_group       os source
0   200       1   34   Russia          Degtyarsk          3  Android    ads
1   201       0   37   Russia             Abakan          0  Android    ads
2   202       1   17   Russia           Smolensk          4  Android    ads
3   203       0   18   Russia             Moscow          1      iOS    ads
4   204       0   36   Russia  Anzhero-Sudzhensk          3  Android    ads
5   205       0   32   Russia         Dugulubgey          3  Android    ads
6   206       1   20   Russia            Kamenka          1  Android    ads
7   207       1   27   Russia            Groznyy          3      iOS    ads
8   208       1   17   Russia               Zima          1  Android    ads
9   209       0   17   Russia       Yuzhnouralsk          1  Android    ads
10  210       0   39  Ukraine           Mykolaiv          3  Android    ads
11  211       1   22  Belarus              Minsk          0      iOS    ads
12  212       1   47   Russia            Podolsk          0      iOS    ads
13  213       1   22  Ukraine          Kamianske          2      iOS    ads
14  214       0   21   Russia             Moscow          4  Android    ads
15  215       1   18  Ukraine          Horodenka          3      iOS    ads
16  216       0   38  Ukraine               Lviv          1  Android    ads
17  217       1   29   Russia              Kansk          3      iOS    ads
18  218       1   25  Belarus              Minsk          2      iOS    ads
19  219       0   36   Russia             Moscow          2  Android    ads

In [33]:
res1 = df[((~df["exp_group"].isin([0, 3])) & (df["country"] != "Russia") )| (df["city"] == "Minsk")]
print(res1["id"].head(4).values)

[211 213 216 218]

In [49]:
res2 = df.groupby("country").agg({"age": ["mean"]})
res2.loc["Cyprus"]["age"]["mean"].round(2)

np.float64(28.07)

In [56]:
res3 = (
    df.groupby(["exp_group", "os"], as_index=False)
      .agg(
          total_users=("id", "count"),
          max_age=("age", "max"),
          min_age=("age", "min")
      )
      [["exp_group", "os", "total_users", "max_age", "min_age"]]
)

res3.to_csv("result.csv", index=False)

In [ ]:
df2 = pd.read_sql(
    """SELECT exp_group, os, count(*),min(age),max(age) FROM "user"
     group by exp_group, os """,
    con=con,
)
df2.head(20)

   exp_group       os  count  min  max
0          0  Android  21234   14   95
1          0      iOS  11489   14   79
2          1  Android  21232   14   92
3          1      iOS  11406   14   87
4          2  Android  21102   14   78
5          2      iOS  11512   14   74
6          3  Android  21319   14   84
7          3      iOS  11449   14   85
8          4  Android  21085   14   84
9          4      iOS  11377   14   78

In [ ]:
df_post = pd.read_sql(
    """SELECT * FROM "post" """,
    con=con,
)
df_post

        id                                               text     topic
0        1  UK economy facing major risks\n\nThe UK manufa...  business
1        2  Aids and climate top Davos agenda\n\nClimate c...  business
2        3  Asian quake hits European shares\n\nShares in ...  business
3        4  India power shares jump on debut\n\nShares in ...  business
4        5  Lacroix label bought by US firm\n\nLuxury good...  business
...    ...                                                ...       ...
7018  7315  OK, I would not normally watch a Farrelly brot...     movie
7019  7316  I give this movie 2 stars purely because of it...     movie
7020  7317  I cant believe this film was allowed to be mad...     movie
7021  7318  The version I saw of this film was the Blockbu...     movie
7022  7319  Piece of subtle art. Maybe a masterpiece. Doub...     movie

[7023 rows x 3 columns]

In [65]:
res4 = (
    df_post.assign(text_len=df_post["text"].str.len())
           .groupby("topic", as_index=False)
           .agg(max_len=("text_len", "max"))
)

res4

           topic  max_len
0       business     5378
1          covid      148
2  entertainment    19004
3          movie    10234
4       politics    25392
5          sport     9438
6           tech    16063

In [74]:
country_counts = df.groupby("country").size()
country_counts

country
Azerbaijan       1542
Belarus          3293
Cyprus            170
Estonia           178
Finland          1599
Kazakhstan       3172
Latvia            175
Russia         143035
Switzerland       162
Turkey           1606
Ukraine          8273
dtype: int64

In [75]:
country_counts[country_counts > 1000].idxmin()

'Azerbaijan'

In [78]:
res5=  df[df["city"] == "Moscow"].groupby("exp_group").agg({"age": ["count","mean"]})

res5[res5["age"]["mean"] > 27.2]

            age
          count       mean
exp_group
1          4414  27.325102
3          4378  27.314299

In [83]:
top_topics = (
    df_post.groupby("topic", as_index=False)
           .agg(post_count=("id", "count"))
           .sort_values("post_count", ascending=False)
           .head(3)
)

print(*top_topics["topic"])

movie covid business

In [88]:
df[df["city"] == "Voronezh"].sort_values(
    by=["age", "exp_group"],
    ascending=[False, True]
)

            id  gender  age country      city  exp_group       os   source
86062    89990       0   71  Russia  Voronezh          0  Android      ads
2242      2441       1   71  Russia  Voronezh          3  Android      ads
13974    14184       1   66  Russia  Voronezh          3  Android      ads
34870    35093       0   65  Russia  Voronezh          0  Android      ads
73460    77284       0   64  Russia  Voronezh          4  Android      ads
...        ...     ...  ...     ...       ...        ...      ...      ...
18069    18278       0   14  Russia  Voronezh          4  Android      ads
29384    29604       0   14  Russia  Voronezh          4  Android      ads
105282  110611       1   14  Russia  Voronezh          4  Android  organic
111121  116446       0   14  Russia  Voronezh          4      iOS  organic
146506  151841       1   14  Russia  Voronezh          4  Android  organic

[1374 rows x 8 columns]

In [ ]:
res6 = pd.read_sql(
    """
select f.post_id, f.time, u.age, u.os from "user" as u
join "feed_action" as f on u.id=f.user_id
where u.city='Omsk' and f.action = 'like'
order by f.time desc
limit 100
""",
con=con,
)

res6.to_csv("res6.csv", index=False)

In [ ]:
pd.read_sql(
    """
select distinct(action) from "feed_action" 
""",
    con=con,
)

  action
0   like
1   view

Найдите город, пользователи которого в возрасте 36 лет 2021-12-01 числа просмотрели запись на тему covid меньше всего раз относительно других городов. Введите его название на английском.

In [ ]:
res7 = pd.read_sql(
    """select u.city, count(*) as count from "user" u
join "feed_action" as f on u.id=f.user_id
join "post" as p on f.post_id=p.id
where u.age=36 and p.topic='covid'  and f.time::date = DATE '2021-12-01'
group by u.city
ORDER BY count;

""",
con=con,
)

res7

                 city  count
0         Arkhangelsk      6
1            Fryazino      9
2          Apsheronsk     10
3               Lubny     10
4                Kirs     11
..                ...    ...
163  Nizhniy Novgorod    151
164          Belgorod    170
165       Novosibirsk    212
166  Saint Petersburg    281
167            Moscow   1975

[168 rows x 2 columns]

> Топ постов
Напишите SQL запрос, используя который вы получите:
- топ N постов по лайкам,
- количество пролайкавших пользователей,
- время последнего лайка.

В качестве ответа напишите через пробел первые 3 ID постов из этого топа.

Сохраните запрос, он может понадобиться в будущем в финальном проекте.

In [9]:
top_posts = pd.read_sql(
    """
SELECT
    f.post_id,
    COUNT(*) AS likes_count,
    COUNT(DISTINCT f.user_id) AS users_count,
    MAX(f.time) AS last_like_time
FROM "feed_action" AS f
WHERE f.action = 'like'
GROUP BY f.post_id
ORDER BY likes_count DESC, f.post_id
LIMIT 3
""",
    con=con,
)

top_posts

   post_id  likes_count  users_count      last_like_time
0     4866        31714        31714 2022-01-01 13:57:43
1     5127        29637        29637 2022-01-05 13:52:17
2     6448        27939        27939 2022-01-22 05:50:39