In [5]:
import pandas as pd
from pathlib import Path

playstore = pd.read_csv(Path("..")/"data"/"playstore_py_lesson_5.csv")
playstore

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10835,10835,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10836,10836,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10837,10837,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10838,10838,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10839,10839,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [8]:
data_head = playstore.head(3)
data_tail = playstore.tail(3)

In [11]:
n_col = playstore.shape[1]
n_row = playstore.shape[0]

10840

In [12]:
playstore['App'].nunique()

9659

In [14]:
rating_missing = playstore['Rating'].isnull().sum()
rating_missing

np.int64(1474)

In [26]:
df1 = playstore[['App', 'Size', 'Genres', 'Current Ver']].loc[:2]
df2 = playstore[['App', 'Size', 'Genres', 'Current Ver']].loc[5:7]
df3 = playstore[['App', 'Size', 'Genres', 'Current Ver']].loc[15:18]
df_final = pd.concat([df1, df2, df3])
df_final.to_csv('df_final.csv', index=True)

In [39]:
unique_playstore = playstore.drop_duplicates(subset='App').reset_index(drop=True)
unique_playstore

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9654,10835,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
9655,10836,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
9656,10837,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
9657,10838,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
9658,10839,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [46]:
playstore.columns = playstore.columns.str.lower().str.replace(' ', '_')
playstore

,unnamed:_0,app,category,rating,reviews,size,installs,type,price,content_rating,genres,last_updated,current_ver,android_ver
0,0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10835,10835,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10836,10836,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10837,10837,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10838,10838,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10839,10839,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [65]:
unique_playstore = playstore.drop_duplicates(subset='app').reset_index(drop=True)
# unique_playstore
type_counts = unique_playstore['type'].value_counts()

free_share = type_counts['Free'] / type_counts.sum()
round(free_share, 2)

np.float64(0.92)

In [77]:
education_playstore = unique_playstore[(unique_playstore['category'] == 'EDUCATION') & (unique_playstore['reviews'] > 1000)].reset_index(drop=True)
education_playstore

,unnamed:_0,app,category,rating,reviews,size,installs,type,price,content_rating,genres,last_updated,current_ver,android_ver
0,699,Duolingo: Learn Languages Free,EDUCATION,4.7,6289924,Varies with device,"100,000,000+",Free,0,Everyone,Education;Education,"August 1, 2018",Varies with device,Varies with device
1,700,TED,EDUCATION,4.6,181893,18M,"10,000,000+",Free,0,Everyone 10+,Education,"July 27, 2018",3.2.5,4.1 and up
2,701,English Communication - Learn English for Chin...,EDUCATION,4.7,2544,18M,"100,000+",Free,0,Everyone,Education,"December 29, 2017",3.1,4.0 and up
3,702,Khan Academy,EDUCATION,4.6,85375,21M,"5,000,000+",Free,0,Everyone,Education,"July 27, 2018",5.0.0,4.1 and up
4,703,Learn English with Wlingua,EDUCATION,4.7,314299,3.3M,"10,000,000+",Free,0,Everyone,Education,"May 2, 2018",1.94.9,4.0 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,848,SoloLearn: Learn to Code for Free,EDUCATION,4.8,256079,7.6M,"1,000,000+",Free,0,Teen,Education,"July 12, 2018",2.2.4,4.0.3 and up
94,849,Kids Learn Languages by Mondly,EDUCATION,4.4,2078,Varies with device,"100,000+",Free,0,Everyone,Education;Education,"December 24, 2017",1.0.2,4.1 and up
95,850,Blinkist - Nonfiction Books,EDUCATION,4.1,16103,13M,"1,000,000+",Free,0,Everyone,Education,"July 31, 2018",5.7.1,4.1 and up
96,853,Toca Life: City,EDUCATION,4.7,31085,24M,"500,000+",Paid,$3.99,Everyone,Education;Pretend Play,"July 6, 2018",1.5-play,4.4 and up
97,854,Toca Life: Hospital,EDUCATION,4.7,3528,24M,"100,000+",Paid,$3.99,Everyone,Education;Pretend Play,"June 12, 2018",1.1.1-play,4.4 and up

In [ ]:
playstore['price']=playstore['price'].str.replace('$', '').astype(float)

unique_playstore['price'] = (
    unique_playstore['price']
    .str.replace('$', '', regex=False)
    .astype(float)
)

In [116]:

result = (pd.pivot_table(
    unique_playstore,
    index=['category', 'type'],
    values=['price', 'rating', 'reviews'],
    aggfunc='mean'
    )
    .rename(columns={'price': 'mean_price', 'rating': 'mean_rating', 'reviews': 'mean_reviews'})
    .round({'mean_price': 2, 'mean_rating': 1, 'mean_reviews': 2})
)

result.to_csv('result_last2.csv', sep=',')
result

                        mean_price  mean_rating  mean_reviews
category          type
ART_AND_DESIGN    Free        0.00          4.3      23230.11
                  Paid        1.99          4.7        722.00
AUTO_AND_VEHICLES Free        0.00          4.2      14140.28
                  Paid        4.49          4.6       1387.67
BEAUTY            Free        0.00          4.3       7476.23
...                            ...          ...           ...
TRAVEL_AND_LOCAL  Paid        4.16          4.1       1506.08
VIDEO_PLAYERS     Free        0.00          4.0     424347.18
                  Paid        2.62          4.1       3341.75
WEATHER           Free        0.00          4.2     171249.62
                  Paid        4.05          4.4      17055.12

[63 rows x 3 columns]

In [113]:
unique_playstore['price'] = pd.to_numeric(
    unique_playstore['price'].astype(str).str.replace('$', '', regex=False),
    errors='coerce'
)

result = (
    unique_playstore.pivot_table(
        index=['category', 'type'],
        values=['price', 'rating', 'reviews'],
        aggfunc='mean'
    )
    .rename(columns={
        'price': 'mean_price',
        'rating': 'mean_rating',
        'reviews': 'mean_reviews'
    })
    .reset_index()
    [['mean_price', 'mean_rating', 'mean_reviews', 'category', 'type']]
    .round({'mean_price': 2, 'mean_rating': 2, 'mean_reviews': 2})
)

result.to_csv('result_last1.csv', sep=',', index=False)
result

    mean_price  mean_rating  mean_reviews           category  type
0         0.00         4.34      23230.11     ART_AND_DESIGN  Free
1         1.99         4.73        722.00     ART_AND_DESIGN  Paid
2         0.00         4.18      14140.28  AUTO_AND_VEHICLES  Free
3         4.49         4.60       1387.67  AUTO_AND_VEHICLES  Paid
4         0.00         4.28       7476.23             BEAUTY  Free
..         ...          ...           ...                ...   ...
58        4.16         4.10       1506.08   TRAVEL_AND_LOCAL  Paid
59        0.00         4.04     424347.18      VIDEO_PLAYERS  Free
60        2.62         4.10       3341.75      VIDEO_PLAYERS  Paid
61        0.00         4.23     171249.62            WEATHER  Free
62        4.05         4.37      17055.12            WEATHER  Paid

[63 rows x 5 columns]