In [29]:
from pathlib import Path
import pandas as pd

data = pd.read_csv(Path("..") / "data" / "data_lesson_5.csv")
data.head()

,id,address,categories,city,cuisines,dateAdded,dateUpdated,latitude,longitude,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
0,AVwc__cikufWRAb51QjV,610 Commercial St,"Restaurant Delivery Service,Restaurants,Pizza,...",Atchison,Restaurant Delivery Service,2016-03-02T11:49:34Z,2017-02-01T18:04:44Z,39.561570,-95.121020,NaN,NaN,2017-02-01T18:04:44Z,NaN,Taco,Gambino's Pizza,KS
1,AVwc__cikufWRAb51QjV,610 Commercial St,"Restaurant Delivery Service,Restaurants,Pizza,...",Atchison,Restaurant Delivery Service,2016-03-02T11:49:34Z,2017-02-01T18:04:44Z,39.561570,-95.121020,NaN,NaN,2016-03-02T11:49:34Z,"Beef, onion, cheddar cheese, lettuce, refried...",Taco,Gambino's Pizza,KS
2,AVwc__dF_7pvs4fz1Ncy,9521 Morton Davis Dr,"Golf Course, American Restaurant, and Resort",Patterson,NaN,2016-10-14T01:58:25Z,2016-10-14T01:58:25Z,37.401855,-121.266703,NaN,NaN,2016-10-14T01:58:25Z,"Beef barbacoa or chicken, spanish rice, pico d...",Smotherd Burrito,Diablo Grande Golf & Country Club,Grayson
3,AVwc__kCByjofQCxkdm-,10550 W I 25 Frontage Rd,Fast Food Restaurant,Longmont,NaN,2016-09-09T17:30:34Z,2016-10-04T05:15:17Z,NaN,NaN,NaN,NaN,2016-09-09T17:30:34Z,NaN,Sausage Burrito,Mcdonald's,Niwot
4,AVwc__WtByjofQCxkdkR,8495 W 3rd St,"Mexican Restaurant Mid-City West,Mexican Resta...",Los Angeles,Mexican,2016-05-19T11:50:25Z,2016-09-11T00:06:37Z,34.080724,-118.389578,NaN,NaN,2016-05-19T11:50:25Z,"Wahoo, avocado, cabbage, pico de gallo and av...",Wahoo Tacogrilled,Baja Fresh Mexican Grill,Bicentennial

In [5]:
df['city'].dtype

dtype('O')

In [6]:
df['latitude'].dtype

dtype('float64')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77260 entries, 0 to 77259
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 77260 non-null  object
 1   address            77260 non-null  object
 2   categories         77260 non-null  object
 3   city               77260 non-null  object
 4   cuisines           38384 non-null  object
 5   dateAdded          77260 non-null  object
 6   dateUpdated        77260 non-null  object
 7   latitude           55636 non-null  float64
 8   longitude          55636 non-null  float64
 9   menus.category     3729 non-null   object
 10  menus.currency     40511 non-null  object
 11  menus.dateSeen     77260 non-null  object
 12  menus.description  29323 non-null  object
 13  menus.name         77260 non-null  object
 14  name               77257 non-null  object
 15  province           77257 non-null  object
dtypes: float64(2), object(14)
memory usage: 9.4+ MB

In [8]:
df.describe()

           latitude     longitude
count  55636.000000  55636.000000
mean      36.694846    -98.713309
std        4.835124     18.245857
min      -31.986438   -159.492690
25%       33.668355   -117.647150
50%       36.047195    -96.682320
75%       40.588380    -82.679930
max       61.219460    115.903696

In [9]:
df.dropna()

,id,address,categories,city,cuisines,dateAdded,dateUpdated,latitude,longitude,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
72,AVwc_6st_7pvs4fz1Mln,95 Matthews Dr,Restaurant,Hilton Head Island,"Japanese, Thai, Hibachi",2015-10-19T20:43:35Z,2016-08-22T11:22:45Z,32.212044,-80.701132,Appetizers Sushi Bar,USD,2016-08-20T00:00:00Z,"Pepper tuna, pepper white tuna, spicy crab mea...",Taco Tara,Okko Hilton Head,SC
242,AVwc_DjlkufWRAb51GPc,2610 Lyndale Ave S,Restaurant,Minneapolis,"American, Bar / Lounge / Bottle Service",2016-08-01T19:18:23Z,2016-08-22T11:27:55Z,44.954945,-93.288246,Main Course,USD,2016-08-20T00:00:00Z,Main i pico slaw i radish i cilantro-lime crem...,Blackened Fish Tacos,French Meadow Cafe & Bluestem Bar,MN
243,AVwc_DjlkufWRAb51GPc,2610 Lyndale Ave S,Restaurant,Minneapolis,"American, Bar / Lounge / Bottle Service",2016-08-01T19:18:23Z,2016-08-22T11:27:55Z,44.954945,-93.288246,Main Course,USD,2016-08-20T00:00:00Z,Blackened organic tempeh i tempeh chorizo i pi...,Blackened Tempeh Tacos,French Meadow Cafe & Bluestem Bar,MN
259,AVwc_DW1_7pvs4fz1DBV,119 W Clay St,"Bistro,American Restaurant,New American Restau...",Mebane,"American Restaurants,American, Contemporary Am...",2016-03-31T02:34:19Z,2017-07-03T17:12:10Z,36.097057,-79.267750,Main,USD,2016-04-24T00:00:00Z,"Grilled or blackened with house made tortilla,...",Shrimp or Mahi Taco,Mebane Downtown Table,NC
261,AVwc_DW1_7pvs4fz1DBV,119 W Clay St,"Bistro,American Restaurant,New American Restau...",Mebane,"American Restaurants,American, Contemporary Am...",2016-03-31T02:34:19Z,2017-07-03T17:12:10Z,36.097057,-79.267750,Starters,USD,2016-04-24T00:00:00Z,"Slow cooked leg of duck, house made tortilla w...",Duck Confit Tacos,Mebane Downtown Table,NC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76997,AVz0WZ18FcQ3k02bDO8m,29 Crown Rd.Building B,Restaurant,Weatherford,Mexican,2017-06-29T14:55:32Z,2017-06-29T14:55:32Z,32.752010,-97.669332,Main,USD,2017-06-28T17:41:09.905Z,"A new favorite Slowsmoked brisket, served in y...",Brisket Tacos,Los Vaqueros - West,TX
76998,AVz0WZ18FcQ3k02bDO8m,29 Crown Rd.Building B,Restaurant,Weatherford,Mexican,2017-06-29T14:55:32Z,2017-06-29T14:55:32Z,32.752010,-97.669332,Main,USD,2017-06-28T17:41:09.905Z,The chefs favorite when he is too busy to sit ...,Johnnys Burrito Bowl,Los Vaqueros - West,TX
76999,AVz0WZ18FcQ3k02bDO8m,29 Crown Rd.Building B,Restaurant,Weatherford,Mexican,2017-06-29T14:55:32Z,2017-06-29T14:55:32Z,32.752010,-97.669332,Main,USD,2017-06-28T17:41:09.905Z,"With chili con queso, Spanish rice and refried...",One Beef or Chicken Burrito,Los Vaqueros - West,TX
77000,AVz0WZf3-gnIPe8DUW4y,2300 Matlock Rd. Suite 21,Restaurant,Mansfield,"Mexican, American, Seafood",2017-06-29T14:55:31Z,2017-06-29T14:55:31Z,32.594093,-97.106282,Ensaladas Salads,USD,2017-06-28T17:33:26.597Z,Seasoned picadillo beef served with fresh mixe...,Ensalada Taco,El Primo's Mexican Grill & Cantina,TX
77014,AVz0WZsS-gnIPe8DUW45,4150 North MacArthur Blvd,Restaurant,Irving,"Steakhouse, American",2017-06-29T14:55:32Z,2017-06-29T14:55:32Z,32.862452,-96.959246,Air,USD,2017-06-28T17:36:57.862Z,peppers onions jack cheese flour tortilla sour...,Beer Can Chicken Tacos,LAW at Four Seasons Dallas,TX

In [11]:
df.loc[404]

id                                         AVwc_kwakufWRAb51L0H
address                                           4 N Walnut St
categories           Restaurant,Pizza Place,American Restaurant
city                                                     Dexter
cuisines                                                Italian
dateAdded                                  2016-04-05T02:01:43Z
dateUpdated                                2016-05-16T23:17:01Z
latitude                                               36.79324
longitude                                             -89.95773
menus.category                                              NaN
menus.currency                                              NaN
menus.dateSeen        2016-05-16T23:17:01Z,2016-04-05T02:01:43Z
menus.description                                           NaN
menus.name                                                 Taco
name                                       Dexter Pizza Company
province                                                     MO
Name: 404, dtype: object

In [13]:
df[df['city'] == 'California'].index

Index([40483, 52930, 52931, 52932, 52933, 52934, 52935, 52936, 52937, 52938,
       52939, 65070],
      dtype='int64')

In [16]:
df[(df['city'] == 'California') & (df['name']=='Taco Bell')].index

Index([52930, 52931, 52932, 52933, 52934, 52935, 52936, 52937, 52938, 52939], dtype='int64')

In [30]:
result = data[((data['city']=='New York') | (data['name']=='Taco Bell')) & (~(data['menus.name'].isin(['Volcano Taco','Fresco Soft Taco'])))]
# data[(data['city']=='New York')]

In [31]:
result

,id,address,categories,city,cuisines,dateAdded,dateUpdated,latitude,longitude,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
131,AVwc_9yCByjofQCxkdRX,322 S. Broadway,"Fast Food,Restaurants,Mexican,Breakfast,Vegeta...",Salem,Mexican,2016-03-28T06:01:51Z,2017-06-27T10:01:48Z,42.755023,-71.209440,NaN,NaN,"2016-03-28T06:01:51Z,2016-06-06T16:15:44Z",NaN,Volcano Burrito,Taco Bell,NH
132,AVwc_9yCByjofQCxkdRX,322 S. Broadway,"Fast Food,Restaurants,Mexican,Breakfast,Vegeta...",Salem,Mexican,2016-03-28T06:01:51Z,2017-06-27T10:01:48Z,42.755023,-71.209440,NaN,NaN,"2016-03-28T06:01:51Z,2016-06-06T16:15:44Z",NaN,Taco 12 Pack,Taco Bell,NH
133,AVwc_9yCByjofQCxkdRX,322 S. Broadway,"Fast Food,Restaurants,Mexican,Breakfast,Vegeta...",Salem,Mexican,2016-03-28T06:01:51Z,2017-06-27T10:01:48Z,42.755023,-71.209440,NaN,NaN,"2016-03-28T06:01:51Z,2016-06-06T16:15:44Z",NaN,Grilled Steak Soft Taco,Taco Bell,NH
135,AVwc_9yCByjofQCxkdRX,322 S. Broadway,"Fast Food,Restaurants,Mexican,Breakfast,Vegeta...",Salem,Mexican,2016-03-28T06:01:51Z,2017-06-27T10:01:48Z,42.755023,-71.209440,NaN,NaN,"2016-03-28T06:01:51Z,2016-06-06T16:15:44Z",NaN,Fresco Grilled Steak Soft Taco,Taco Bell,NH
136,AVwc_9yCByjofQCxkdRX,322 S. Broadway,"Fast Food,Restaurants,Mexican,Breakfast,Vegeta...",Salem,Mexican,2016-03-28T06:01:51Z,2017-06-27T10:01:48Z,42.755023,-71.209440,NaN,NaN,"2016-03-28T06:01:51Z,2016-06-06T16:15:44Z",NaN,Fresco Crunchy Taco,Taco Bell,NH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76904,AVweZN9nByjofQCxxz4o,754 Ninth Ave,Restaurant,New York,"Mexican, American, Traditional Mexican",2015-10-19T20:44:15Z,2016-08-22T11:24:07Z,40.763858,-73.988327,Tacos,USD,2016-08-21T00:00:00Z,NaN,Trio of Tacos,Hell's Kitchen,Nyc
76905,AVweZN9nByjofQCxxz4o,754 Ninth Ave,Restaurant,New York,"Mexican, American, Traditional Mexican",2015-10-19T20:44:15Z,2016-08-22T11:24:07Z,40.763858,-73.988327,"Huevos, Etc.",USD,2016-08-07T00:00:00Z,NaN,Brunch Burrito,Hell's Kitchen,Nyc
76906,AVweZN9nByjofQCxxz4o,754 Ninth Ave,Restaurant,New York,"Mexican, American, Traditional Mexican",2015-10-19T20:44:15Z,2016-08-22T11:24:07Z,40.763858,-73.988327,Botanas,USD,2016-08-07T00:00:00Z,NaN,Grilled Chicken Mini Burrito,Hell's Kitchen,Nyc
76907,AVweZN9nByjofQCxxz4o,754 Ninth Ave,Restaurant,New York,"Mexican, American, Traditional Mexican",2015-10-19T20:44:15Z,2016-08-22T11:24:07Z,40.763858,-73.988327,Botanas,USD,2016-08-07T00:00:00Z,with pumpkin seed guacamole,Grilled Vegetable Mini Burrito,Hell's Kitchen,Nyc
76908,AVweZN9nByjofQCxxz4o,754 Ninth Ave,Restaurant,New York,"Mexican, American, Traditional Mexican",2015-10-19T20:44:15Z,2016-08-22T11:24:07Z,40.763858,-73.988327,Main,NaN,2016-08-21T00:00:00Z,NaN,Burritos,Hell's Kitchen,Nyc

In [33]:
result = data[~(data['menus.currency'].isna())]
result

,id,address,categories,city,cuisines,dateAdded,dateUpdated,latitude,longitude,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
15,AVwc_1y6kufWRAb51O6w,906 Park Ave SW,"Coffee Shop,Restaurants,Coffeehouses",Albuquerque,Coffee Shops,2016-06-05T20:15:56Z,2017-07-06T13:28:29Z,35.085320,-106.657616,NaN,USD,"2016-06-05T20:15:56Z,2016-10-20T07:09:38Z","Potatoes, onion, peppers, mushroom, avocado, b...",Mondo Veggie Burrito,Java Joe's,NM
16,AVwc_1y6kufWRAb51O6w,906 Park Ave SW,"Coffee Shop,Restaurants,Coffeehouses",Albuquerque,Coffee Shops,2016-06-05T20:15:56Z,2017-07-06T13:28:29Z,35.085320,-106.657616,NaN,USD,"2016-06-05T20:15:56Z,2016-10-20T07:09:38Z","Grilled tofu, potatoes and your choice of chil...",Tofu Burrito,Java Joe's,NM
17,AVwc_1y6kufWRAb51O6w,906 Park Ave SW,"Coffee Shop,Restaurants,Coffeehouses",Albuquerque,Coffee Shops,2016-06-05T20:15:56Z,2017-07-06T13:28:29Z,35.085320,-106.657616,NaN,USD,"2016-06-05T20:15:56Z,2016-10-20T07:09:38Z",NaN,Black Bean Burrito,Java Joe's,NM
18,AVwc_2OQ_7pvs4fz1L5H,100 W Higgins Rd,Restaurant,Barrington,"Mexican, Latin American",2016-07-26T17:39:41Z,2016-08-26T05:25:56Z,42.074974,-88.189151,NaN,USD,2016-08-22T00:00:00Z,NaN,Burrito De Rajas,Mago Grill & Cantina - South Barrington,Fox Rv Vly Gn
19,AVwc_2OQ_7pvs4fz1L5H,100 W Higgins Rd,Restaurant,Barrington,"Mexican, Latin American",2016-07-26T17:39:41Z,2016-08-26T05:25:56Z,42.074974,-88.189151,NaN,USD,2016-08-22T00:00:00Z,"lettuce, chihuahua cheese, black beans, mexica...",Taco,Mago Grill & Cantina - South Barrington,Fox Rv Vly Gn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77255,AVzRLlQNLD2H7whiWdH_,3919 24th St.,Restaurant,San Francisco,Mexican,2017-06-22T19:01:33Z,2017-06-22T19:01:33Z,37.751392,-122.430180,NaN,USD,2017-06-22T16:40:06.448Z,"meat, rice, beans, guacamole, sour cream, chee...",Super Burrito,La Casona Taqueria,California
77256,AVzRLlQNLD2H7whiWdH_,3919 24th St.,Restaurant,San Francisco,Mexican,2017-06-22T19:01:33Z,2017-06-22T19:01:33Z,37.751392,-122.430180,NaN,USD,2017-06-22T16:40:06.448Z,"melted cheese, rice, beans & salsa",Steamed Broccoli Burrito,La Casona Taqueria,California
77257,AVzRLlQNLD2H7whiWdH_,3919 24th St.,Restaurant,San Francisco,Mexican,2017-06-22T19:01:33Z,2017-06-22T19:01:33Z,37.751392,-122.430180,NaN,USD,2017-06-22T16:40:06.448Z,meat & salsa,Regular Taco,La Casona Taqueria,California
77258,AVzRLlQNLD2H7whiWdH_,3919 24th St.,Restaurant,San Francisco,Mexican,2017-06-22T19:01:33Z,2017-06-22T19:01:33Z,37.751392,-122.430180,NaN,USD,2017-06-22T16:40:06.448Z,"meat, rice, beans & salsa",Regular Burrito,La Casona Taqueria,California
77259,AVzRLlQNLD2H7whiWdH_,3919 24th St.,Restaurant,San Francisco,Mexican,2017-06-22T19:01:33Z,2017-06-22T19:01:33Z,37.751392,-122.430180,NaN,USD,2017-06-22T16:40:06.448Z,"stuffed with rice, beans, meat, topped with en...",Azteca Burrito,La Casona Taqueria,California

In [39]:
data.groupby(['menus.currency']).nunique(dropna=True)['id']

menus.currency
EUR        1
USD    10464
Name: id, dtype: int64

In [36]:
data[data['menus.currency']=='EUR']

,id,address,categories,city,cuisines,dateAdded,dateUpdated,latitude,longitude,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
60187,AVwdr2vRkufWRAb58UrX,Grindelallee 79,"salate,burritos,quesadillas,salsa,beilagen,ext...",Ashburn,"salate,burritos,quesadillas,salsa,beilagen,extras",2017-04-03T16:03:15Z,2017-07-06T18:54:16Z,53.567287,9.980289,NaN,EUR,2017-06-28T16:21:38.309Z,mit zart geschmortes Rindfleisch in milder Chi...,Special Burrito,Qrito,VA
60188,AVwdr2vRkufWRAb58UrX,Grindelallee 79,"salate,burritos,quesadillas,salsa,beilagen,ext...",Ashburn,"salate,burritos,quesadillas,salsa,beilagen,extras",2017-04-03T16:03:15Z,2017-07-06T18:54:16Z,53.567287,9.980289,NaN,EUR,2017-06-28T16:21:38.289Z,mit zart geschmortem Rindfleisch milder ChiliM...,Beef Ranchera Burrito,Qrito,VA
60189,AVwdr2vRkufWRAb58UrX,Grindelallee 79,"salate,burritos,quesadillas,salsa,beilagen,ext...",Ashburn,"salate,burritos,quesadillas,salsa,beilagen,extras",2017-04-03T16:03:15Z,2017-07-06T18:54:16Z,53.567287,9.980289,NaN,EUR,2017-06-28T16:21:38.306Z,mit zart geschmortem Rindfleisch in milder Chi...,Beef Caliente Burrito sehr scharf,Qrito,VA
60190,AVwdr2vRkufWRAb58UrX,Grindelallee 79,"salate,burritos,quesadillas,salsa,beilagen,ext...",Ashburn,"salate,burritos,quesadillas,salsa,beilagen,extras",2017-04-03T16:03:15Z,2017-07-06T18:54:16Z,53.567287,9.980289,NaN,EUR,2017-06-28T16:21:38.295Z,mit geschmortem und anschlieend gegrilltem Sch...,Carnitas Burrito,Qrito,VA
60191,AVwdr2vRkufWRAb58UrX,Grindelallee 79,"salate,burritos,quesadillas,salsa,beilagen,ext...",Ashburn,"salate,burritos,quesadillas,salsa,beilagen,extras",2017-04-03T16:03:15Z,2017-07-06T18:54:16Z,53.567287,9.980289,NaN,EUR,2017-06-28T16:21:38.321Z,klassische Tofuvariante mit einer wrzigen Chil...,Tofu Poblano Burrito vegan,Qrito,VA
60192,AVwdr2vRkufWRAb58UrX,Grindelallee 79,"salate,burritos,quesadillas,salsa,beilagen,ext...",Ashburn,"salate,burritos,quesadillas,salsa,beilagen,extras",2017-04-03T16:03:15Z,2017-07-06T18:54:16Z,53.567287,9.980289,NaN,EUR,2017-06-28T16:21:38.302Z,klassische Tofuvariante mit einer wrzigen Chil...,Tofu Poblano Burrito,Qrito,VA
60193,AVwdr2vRkufWRAb58UrX,Grindelallee 79,"salate,burritos,quesadillas,salsa,beilagen,ext...",Ashburn,"salate,burritos,quesadillas,salsa,beilagen,extras",2017-04-03T16:03:15Z,2017-07-06T18:54:16Z,53.567287,9.980289,NaN,EUR,2017-06-28T16:21:38.315Z,SojaSchnetzel gegrilltem Gemse Reis mit rotem ...,SojaHack Burrito vegan,Qrito,VA
60194,AVwdr2vRkufWRAb58UrX,Grindelallee 79,"salate,burritos,quesadillas,salsa,beilagen,ext...",Ashburn,"salate,burritos,quesadillas,salsa,beilagen,extras",2017-04-03T16:03:15Z,2017-07-06T18:54:16Z,53.567287,9.980289,NaN,EUR,2017-06-28T16:21:38.313Z,mit lecker gewrztes Rinderhackfleisch Knusprig...,Crispy Cheesy Burrito,Qrito,VA
60195,AVwdr2vRkufWRAb58UrX,Grindelallee 79,"salate,burritos,quesadillas,salsa,beilagen,ext...",Ashburn,"salate,burritos,quesadillas,salsa,beilagen,extras",2017-04-03T16:03:15Z,2017-07-06T18:54:16Z,53.567287,9.980289,NaN,EUR,2017-06-28T16:21:38.293Z,Hhnchenbrustfilet in einer wrzigen ChiliErdnus...,Chicken Poblano Burrito,Qrito,VA
60196,AVwdr2vRkufWRAb58UrX,Grindelallee 79,"salate,burritos,quesadillas,salsa,beilagen,ext...",Ashburn,"salate,burritos,quesadillas,salsa,beilagen,extras",2017-04-03T16:03:15Z,2017-07-06T18:54:16Z,53.567287,9.980289,NaN,EUR,2017-06-28T16:21:38.318Z,mit gegrilltes Gemse spanischer Reis schwarze ...,Vegetable Burrito vegan,Qrito,VA
60197,AVwdr2vRkufWRAb58UrX,Grindelallee 79,"salate,burritos,quesadillas,salsa,beilagen,ext...",Ashburn,"salate,burritos,quesadillas,salsa,beilagen,extras",2017-04-03T16:03:15Z,2017-07-06T18:54:16Z,53.567287,9.980289,NaN,EUR,2017-06-28T16:21:38.312Z,mit gegrilltem Gemse spanischer Reis schwarze ...,Vegetable Burrito,Qrito,VA
60198,AVwdr2vRkufWRAb58UrX,Grindelallee 79,"salate,burritos,quesadillas,salsa,beilagen,ext...",Ashburn,"salate,burritos,quesadillas,salsa,beilagen,extras",2017-04-03T16:03:15Z,2017-07-06T18:54:16Z,53.567287,9.980289,NaN,EUR,2017-06-28T16:21:38.319Z,klassische Tofuvariante mit gegrilltem Gemse R...,Tofu Verdura Burrito vegan,Qrito,VA
60199,AVwdr2vRkufWRAb58UrX,Grindelallee 79,"salate,burritos,quesadillas,salsa,beilagen,ext...",Ashburn,"salate,burritos,quesadillas,salsa,beilagen,extras",2017-04-03T16:03:15Z,2017-07-06T18:54:16Z,53.567287,9.980289,NaN,EUR,2017-06-28T16:21:38.300Z,klassische Tofuvariante mit gegrilltem Gemse R...,Tofu Verdura Burrito,Qrito,VA
60200,AVwdr2vRkufWRAb58UrX,Grindelallee 79,"salate,burritos,quesadillas,salsa,beilagen,ext...",Ashburn,"salate,burritos,quesadillas,salsa,beilagen,extras",2017-04-03T16:03:15Z,2017-07-06T18:54:16Z,53.567287,9.980289,NaN,EUR,2017-06-28T16:21:38.305Z,SojaSchnetzel spanischer Reis schwarze Bohnen ...,SojaHack Burrito,Qrito,VA
60201,AVwdr2vRkufWRAb58UrX,Grindelallee 79,"salate,burritos,quesadillas,salsa,beilagen,ext...",Ashburn,"salate,burritos,quesadillas,salsa,beilagen,extras",2017-04-03T16:03:15Z,2017-07-06T18:54:16Z,53.567287,9.980289,NaN,EUR,2017-06-28T16:21:38.290Z,Hhnchenbrustfilet mit einer fruchtigen Sauce a...,Chicken California Burrito,Qrito,VA
60202,AVwdr2vRkufWRAb58UrX,Grindelallee 79,"salate,burritos,quesadillas,salsa,beilagen,ext...",Ashburn,"salate,burritos,quesadillas,salsa,beilagen,extras",2017-04-03T16:03:15Z,2017-07-06T18:54:16Z,53.567287,9.980289,NaN,EUR,2017-06-28T16:21:38.298Z,mit lecker gewrztes Rinderhackfleisch spanisch...,Delano Picadillo Burrito,Qrito,VA

In [44]:
data['categories']

0        Restaurant Delivery Service,Restaurants,Pizza,...
1        Restaurant Delivery Service,Restaurants,Pizza,...
2             Golf Course, American Restaurant, and Resort
3                                     Fast Food Restaurant
4        Mexican Restaurant Mid-City West,Mexican Resta...
                               ...
77255                                           Restaurant
77256                                           Restaurant
77257                                           Restaurant
77258                                           Restaurant
77259                                           Restaurant
Name: categories, Length: 77260, dtype: object

In [45]:
data[['categories']]

                                              categories
0      Restaurant Delivery Service,Restaurants,Pizza,...
1      Restaurant Delivery Service,Restaurants,Pizza,...
2           Golf Course, American Restaurant, and Resort
3                                   Fast Food Restaurant
4      Mexican Restaurant Mid-City West,Mexican Resta...
...                                                  ...
77255                                         Restaurant
77256                                         Restaurant
77257                                         Restaurant
77258                                         Restaurant
77259                                         Restaurant

[77260 rows x 1 columns]

In [47]:
data.groupby('city').size().sort_values(ascending=False).head(5)

city
San Diego        1924
Los Angeles      1603
Chicago          1186
San Francisco    1120
New York         1085
dtype: int64

In [48]:
", ".join(
    data.groupby('city')
        .size()
        .sort_values(ascending=False)
        .head(5)
        .index
)

'San Diego, Los Angeles, Chicago, San Francisco, New York'

In [51]:
data[data['name']=='Taco Bell'].groupby('city').size().sort_values(ascending=False)

city
Indianapolis    84
Charleston      63
Columbus        63
Tampa           62
Albuquerque     42
                ..
New Lenox        1
Parker           1
Plainville       1
Troutdale        1
Tuscaloosa       1
Length: 134, dtype: int64

In [55]:
data[data['name']=='Taco Bell']['city'].value_counts().head(5)

city
Indianapolis    84
Columbus        63
Charleston      63
Tampa           62
Albuquerque     42
Name: count, dtype: int64

In [58]:
result = data
result['dateAdded'] = pd.to_datetime(result['dateAdded'])
result[result['dateAdded'].dt.month == 10]

,id,address,categories,city,cuisines,dateAdded,dateUpdated,latitude,longitude,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
2,AVwc__dF_7pvs4fz1Ncy,9521 Morton Davis Dr,"Golf Course, American Restaurant, and Resort",Patterson,NaN,2016-10-14 01:58:25+00:00,2016-10-14T01:58:25Z,37.401855,-121.266703,NaN,NaN,2016-10-14T01:58:25Z,"Beef barbacoa or chicken, spanish rice, pico d...",Smotherd Burrito,Diablo Grande Golf & Country Club,Grayson
21,AVwc_3Kp_7pvs4fz1MDQ,116 Pleasant St,"Restaurant,Seafood Restaurants,Take Out Restau...",Easthampton,"American,Seafood Restaurants",2015-10-26 23:10:06+00:00,2016-09-19T17:41:29Z,42.273525,-72.663124,NaN,USD,2016-09-19T17:41:29Z,"Crispy house-smoked pork belly, hoisin sauce, ...",Korean Pork Belly Tacos,Riff's Joint,Westhampton
22,AVwc_3Kp_7pvs4fz1MDQ,116 Pleasant St,"Restaurant,Seafood Restaurants,Take Out Restau...",Easthampton,"American,Seafood Restaurants",2015-10-26 23:10:06+00:00,2016-09-19T17:41:29Z,42.273525,-72.663124,NaN,USD,2016-09-19T17:41:29Z,"Black beans, corn and black bean salsa, guacam...",Speedy Gonzalez Burrito,Riff's Joint,Westhampton
23,AVwc_3Kp_7pvs4fz1MDQ,116 Pleasant St,"Restaurant,Seafood Restaurants,Take Out Restau...",Easthampton,"American,Seafood Restaurants",2015-10-26 23:10:06+00:00,2016-09-19T17:41:29Z,42.273525,-72.663124,NaN,USD,2016-09-19T17:41:29Z,"Black beans, jasmine rice and peanut slaw",Thai Dyed Burrito,Riff's Joint,Westhampton
24,AVwc_3Kp_7pvs4fz1MDQ,116 Pleasant St,"Restaurant,Seafood Restaurants,Take Out Restau...",Easthampton,"American,Seafood Restaurants",2015-10-26 23:10:06+00:00,2016-09-19T17:41:29Z,42.273525,-72.663124,NaN,USD,2016-09-19T17:41:29Z,"Black beans, cheddar, salsa, rice, sour cream,...",Burrito Supreme,Riff's Joint,Westhampton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76927,AVweZtCQByjofQCxx3uK,11688 Us 23,Fast Food Restaurant,Waverly,NaN,2015-10-22 19:23:28+00:00,2016-08-09T10:11:49Z,39.119935,-82.993279,NaN,NaN,2015-10-22T19:23:28Z,NaN,Sausage Burrito,Mcdonalds,OH
76946,AVweZZ31IN2L1WUf4jVT,2521 Bagby,Restaurant,Houston,"Continental, Contemporary European, Global, In...",2015-10-19 20:42:46+00:00,2016-08-22T11:26:45Z,29.748747,-95.379022,Specialty Bar Menu,USD,2016-04-24T00:00:00Z,NaN,Ahi Tuna Crispy Taco (2),Charivari,TX
76947,AVweZZ31IN2L1WUf4jVT,2521 Bagby,Restaurant,Houston,"Continental, Contemporary European, Global, In...",2015-10-19 20:42:46+00:00,2016-08-22T11:26:45Z,29.748747,-95.379022,Specialty Bar Menu,USD,2016-08-20T00:00:00Z,NaN,Pork Shank (schweinehaxe) Taco (2),Charivari,TX
76948,AVweZ-ZKIN2L1WUf4n9V,110 W Hubbard,Restaurant,Chicago,"Contemporary European, Bar / Lounge / Bottle S...",2015-10-19 20:37:03+00:00,2016-08-09T02:40:48Z,41.890262,-87.631646,Beginners,USD,2016-08-07T00:00:00Z,"Corn tortilla, avocado, sesame, soy sauce, mar...",Tuna Tartare Tacos,Hubbard Inn,IL
76949,AVweZ-ZKIN2L1WUf4n9V,110 W Hubbard,Restaurant,Chicago,"Contemporary European, Bar / Lounge / Bottle S...",2015-10-19 20:37:03+00:00,2016-08-09T02:40:48Z,41.890262,-87.631646,Lunch Plates,USD,2016-04-24T00:00:00Z,NaN,Tuna Tartare Taco,Hubbard Inn,IL

In [59]:
data[data['categories'].str.contains('Pizza', na=False)].head(5)

,id,address,categories,city,cuisines,dateAdded,dateUpdated,latitude,longitude,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
0,AVwc__cikufWRAb51QjV,610 Commercial St,"Restaurant Delivery Service,Restaurants,Pizza,...",Atchison,Restaurant Delivery Service,2016-03-02 11:49:34+00:00,2017-02-01T18:04:44Z,39.561570,-95.12102,NaN,NaN,2017-02-01T18:04:44Z,NaN,Taco,Gambino's Pizza,KS
1,AVwc__cikufWRAb51QjV,610 Commercial St,"Restaurant Delivery Service,Restaurants,Pizza,...",Atchison,Restaurant Delivery Service,2016-03-02 11:49:34+00:00,2017-02-01T18:04:44Z,39.561570,-95.12102,NaN,NaN,2016-03-02T11:49:34Z,"Beef, onion, cheddar cheese, lettuce, refried...",Taco,Gambino's Pizza,KS
66,AVwc_59U_7pvs4fz1Md3,3250 Kennedy Cir,"Pizza,Take Out Restaurants,Caterers,Restaurant...",Dubuque,Pizza,2016-03-29 04:45:06+00:00,2016-05-05T12:40:51Z,42.505264,-90.72141,NaN,NaN,"2016-05-05T12:40:51Z,2016-03-29T04:45:06Z",NaN,Taco Supreme,Falbo Bros Pizzeria,IA
67,AVwc_59U_7pvs4fz1Md3,3250 Kennedy Cir,"Pizza,Take Out Restaurants,Caterers,Restaurant...",Dubuque,Pizza,2016-03-29 04:45:06+00:00,2016-05-05T12:40:51Z,42.505264,-90.72141,NaN,NaN,"2016-05-05T12:40:51Z,2016-03-29T04:45:06Z",NaN,Taco,Falbo Bros Pizzeria,IA
158,AVwc_AmZkufWRAb51FxA,133 Howard St,"Pizza,Restaurants",Braintree,Pizza,2016-09-19 17:43:53+00:00,2016-09-19T17:43:53Z,42.233826,-70.98024,NaN,USD,2016-09-19T17:43:53Z,"Large salsa, pizza cheese, hamburger, hot pepp...",Mexican Taco,New England House of Pizza,Braintree Hld

In [71]:
data['update_delta']= (pd.to_datetime(data['dateUpdated']) - pd.to_datetime(data['dateAdded'])).dt.days
data['update_delta'].mean()

np.float64(326.22456639917164)

In [72]:
data['update_delta'].median()

np.float64(364.0)

In [75]:
data['categories'].str.split(',')

0        [Restaurant Delivery Service, Restaurants, Piz...
1        [Restaurant Delivery Service, Restaurants, Piz...
2         [Golf Course,  American Restaurant,  and Resort]
3                                   [Fast Food Restaurant]
4        [Mexican Restaurant Mid-City West, Mexican Res...
                               ...
77255                                         [Restaurant]
77256                                         [Restaurant]
77257                                         [Restaurant]
77258                                         [Restaurant]
77259                                         [Restaurant]
Name: categories, Length: 77260, dtype: object

In [95]:
category_count = data['categories'].apply(lambda value: len(str(value).split(',')))
filtered_data = data[category_count > 20]

result = (
    filtered_data.groupby('province', as_index=False)['longitude']
    .min()
    .round({'longitude': 3})
)

In [96]:
result.to_csv('result.csv', sep=';', index=False)
result

        province  longitude
0             AZ   -110.136
1             CA   -122.417
2             DC    -77.075
3          G P O    -73.990
4             KY    -87.455
5             MA    -71.055
6             MD    -77.453
7             NY    -76.794
8   St Simons Is    -81.394
9             TX    -94.939
10            VA    -77.093
11            WA   -122.383
12            WI    -89.377